import { makeRoom } from './metroidvaniaLayouts';
import { makeSceneRoom } from './sceneLayouts';
import type { Level } from './types';

export const levels: Level[] = [
  {
    name: "Pip's Giant Bedroom",
    chapter: 'Room 1 · The awakening',
    accent: '#ffbd72',
    enemyTheme: 'bedroom',
    background: '/assets/giant-bedroom-map-hidden.png',
    hint: 'The furniture is the map. Some memories hide below.',
    gimmick: 'Sleepy shadows guard the hidden routes.',
    ...makeRoom({ secretNames: ['The Drawer Hollow', 'Under the Bed'] }),
  },
  {
    name: 'Moonlit Greenhouse',
    chapter: 'Room 2 · Wild thoughts',
    accent: '#8ee59b',
    enemyTheme: 'greenhouse',
    background: '/assets/moonlit-greenhouse.png',
    hint: 'Climb past the leaves and listen for hollow roots.',
    gimmick: 'Leaf-crowned shadows close in from the vines.',
    ...makeSceneRoom({ pattern: 'steps', reverse: true }),
  },
  {
    name: 'Clockwork Loft',
    chapter: 'Room 3 · Borrowed time',
    accent: '#f3b562',
    enemyTheme: 'clockwork',
    background: '/assets/clockwork-loft.png',
    hint: 'Follow the gears upward, but search below the ticking floor.',
    gimmick: 'Wound-up hunters never stop moving.',
    ...makeSceneRoom({ pattern: 'climb' }),
  },
  {
    name: 'Forgotten Studio',
    chapter: 'Room 4 · Unfinished ideas',
    accent: '#ff829b',
    enemyTheme: 'studio',
    background: '/assets/forgotten-studio.png',
    hint: 'Old paintings cover more than walls.',
    gimmick: 'Paint-stained shadows leap between unfinished work.',
    ...makeSceneRoom({ pattern: 'zigzag', reverse: true }),
  },
  {
    name: 'Hidden Theatre',
    chapter: 'Room 5 · Behind the curtain',
    accent: '#d7a0ff',
    enemyTheme: 'theatre',
    background: '/assets/hidden-theatre.png',
    hint: 'Not every curtain belongs to the stage.',
    gimmick: 'Masked shadows perform their hunt in pairs.',
    ...makeSceneRoom({ pattern: 'steps' }),
  },
  {
    name: 'Storm Map Room',
    chapter: 'Room 6 · A world in motion',
    accent: '#76d7ff',
    enemyTheme: 'storm',
    background: '/assets/storm-map-room.png',
    hint: 'The safest route is rarely the straightest one.',
    gimmick: 'Lightning shadows attack in sudden bursts.',
    ...makeSceneRoom({ pattern: 'climb', reverse: true }),
  },
  {
    name: 'Midnight Workshop',
    chapter: 'Room 7 · Made by hand',
    accent: '#e8d477',
    enemyTheme: 'workshop',
    background: '/assets/craft-room.png',
    hint: 'Tools can build a path—or conceal one.',
    gimmick: 'Goggled shadows guard every invention.',
    ...makeSceneRoom({ pattern: 'zigzag' }),
  },
  {
    name: 'Attic of Echoes',
    chapter: 'Room 8 · Things remembered',
    accent: '#b6adff',
    enemyTheme: 'attic',
    background: '/assets/attic-night.png',
    hint: 'Dust settles where footsteps do not.',
    gimmick: 'Ghostly shadows drift through forgotten corners.',
    ...makeSceneRoom({ pattern: 'steps', reverse: true }),
  },
  {
    name: 'The Last Dream',
    chapter: 'Room 9 · Wake up, Pip',
    accent: '#ff9fd6',
    enemyTheme: 'dream',
    background: '/assets/last-dream.png',
    hint: 'Every path you learned returns one final time.',
    gimmick: 'Dream shadows remember how you escaped before.',
    ...makeSceneRoom({ pattern: 'climb' }),
  },
];
